import tkinter as tk
import tkinter as ttk
root=tk.Tk()
root.title("STUDENT REGISTRATION FORM")
root.geometry("500x700")
root.config(bg="gray")
frame=tk.Frame(root,highlightbackground="skyblue",highlightthickness=10,width=500,height=700)
frame.place(x=0,y=0)
frame1=tk.Frame(root,highlightbackground="violet",highlightthickness=2,width=480,height=680)
frame1.place(x=10,y=10)
label1=tk.Label(root,text="STUDENT REGISTRATION FORM",fg="pink",font=("Helvetica",18,"bold"))
label1.place(x=70,y=30)
lab2=tk.Label(root,text="First Name")
lab2.place(x=20,y=70)
entr1=tk.Entry(root,text="enter first name",width=50)
entr1.place(x=100,y=70)
lab3=tk.Label(root,text="Last Name")
lab3.place(x=20,y=110)
entr2=tk.Entry(root,width=50)
entr2.place(x=100,y=110)
lab4=tk.Label(root,text="Gender")
lab4.place(x=20,y=150)
Gender=tk.IntVar()
r1=tk.Radiobutton(root,text="Male",variable=Gender,value="male")
r1.place(x=80,y=150)
r2=tk.Radiobutton(root,text="Female",variable=Gender,value="female")
r2.place(x=160,y=150)

root.mainloop()